### PR TITLE
Jan productsell

### LINKED ISSUE #1: Customer can add a product to sell
**Given** the user is not authenticated
**When** any view renders
**Then** the *Sell a Product* affordance will not be visible

**Given** the user is authenticated
**When** the user clicks on the *Sell a product* button in the menu bar
**Then** the user will be presented with a product form

**Given** the user has filled in all fields of the product form with valid information
**When** the user clicks the *Sell* button
**Then** the user will be redirected to the product detail view for that product

**Given** the user has filled in all fields of the product form with any invalid information
**When** the user clicks the *Sell* button
**Then** the user will be immediately notified with error information for each invalid value

### PR DESCRIPTION
**Pull request by jamesnitz**
# Description

Users can add a product, MUST select a category, and then are directed to the details page

Fixes #1 #10 #13 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions
DO THIS TWICE
1. Select sell a product
2. Enter in the requisite information **leaving off the category**
3. confirm the alert window appears and your previous info also remains
4. select a category and create it
5. make sure you're on the detail page with the information you just added visible

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by wggreen — APPROVED** [review]
Cool button

**Comment by garrettfreshwater-nss** [comment]
Nice work

**Comment by garrettfreshwater-nss** [comment]
Nice Work

**Comment by garrettfreshwater-nss** [comment]
Great

**Review by garrettfreshwater-nss — APPROVED** [review]
Great Wrk

**Pull request merged**
